<a href="https://colab.research.google.com/github/narain-priyanka/vision_machine_learning/blob/master/TensorFlow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [4]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [6]:
tensor_one_d = tf.constant([2,0,3])
print(tensor_one_d)

tf.Tensor([2 3], shape=(2,), dtype=int32)


In [8]:
tensor_two_d = tf.constant([[2,0,3],[1,0,2],[-1,0,3.0]]
                           )
print(tensor_two_d)

tf.Tensor(
[[ 2.  0.  3.]
 [ 1.  0.  2.]
 [-1.  0.  3.]], shape=(3, 3), dtype=float32)


In [11]:
tensor_three_d = tf.constant([
  [[2,0,3],
   [1,0,2]],
  [[2,0,3],
   [1,0,2]],
  [[2,0,3],
   [1,0,2]],
  [[2,0,3],
   [1,0,2]]
  ])
print(tensor_three_d)

tf.Tensor(
[[[2 0 3]
  [1 0 2]]

 [[2 0 3]
  [1 0 2]]

 [[2 0 3]
  [1 0 2]]

 [[2 0 3]
  [1 0 2]]], shape=(4, 2, 3), dtype=int32)


In [12]:
print(tensor_three_d.shape)

(4, 2, 3)


In [15]:
print(tensor_three_d.ndim)

3


In [16]:
tensor_four_d = tf.constant([
    [
  [[2,0,3],
   [1,0,2]],
  [[2,0,3],
   [1,0,2]],
  [[2,0,3],
   [1,0,2]],
  [[2,0,3],
   [1,0,2]]
  ], [
  [[2,0,3],
   [1,0,2]],
  [[2,0,3],
   [1,0,2]],
  [[2,0,3],
   [1,0,2]],
  [[2,0,3],
   [1,0,2]]
  ], [
  [[2,0,3],
   [1,0,2]],
  [[2,0,3],
   [1,0,2]],
  [[2,0,3],
   [1,0,2]],
  [[2,0,3],
   [1,0,2]]
  ]] )
print(tensor_four_d)

tf.Tensor(
[[[[2 0 3]
   [1 0 2]]

  [[2 0 3]
   [1 0 2]]

  [[2 0 3]
   [1 0 2]]

  [[2 0 3]
   [1 0 2]]]


 [[[2 0 3]
   [1 0 2]]

  [[2 0 3]
   [1 0 2]]

  [[2 0 3]
   [1 0 2]]

  [[2 0 3]
   [1 0 2]]]


 [[[2 0 3]
   [1 0 2]]

  [[2 0 3]
   [1 0 2]]

  [[2 0 3]
   [1 0 2]]

  [[2 0 3]
   [1 0 2]]]], shape=(3, 4, 2, 3), dtype=int32)


In [17]:
print(tensor_four_d.shape)

(3, 4, 2, 3)


In [18]:
print(tensor_four_d.ndim)

4


In [33]:
tensor_one_dd = tf.constant([2,0.0,3], dtype=tf.float16)
casted_tensor = tf.cast(tensor_one_dd,dtype= tf.bool)
casted_tensor2 = tf.cast(tensor_one_dd,dtype= tf.int32)
print(tensor_one_dd)
print(casted_tensor)
print(casted_tensor2)

tf.Tensor([2. 0. 3.], shape=(3,), dtype=float16)
tf.Tensor([ True False  True], shape=(3,), dtype=bool)
tf.Tensor([2 0 3], shape=(3,), dtype=int32)


In [36]:
tensor_string = tf.constant("hello world")
print(tensor_string)
tensor_string2 = tf.constant(["hello world", "hi"])
print(tensor_string2)

tf.Tensor(b'hello world', shape=(), dtype=string)
tf.Tensor([b'hello world' b'hi'], shape=(2,), dtype=string)


In [37]:
import numpy as np

In [39]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]
