<a href="https://colab.research.google.com/github/narain-priyanka/vision_machine_learning/blob/master/Tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [3]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_2d = tf.constant([
      [2,-3,1],
      [2,-3,1]
])
print(tensor_2d)

tf.Tensor(
[[ 2 -3  1]
 [ 2 -3  1]], shape=(2, 3), dtype=int32)


In [7]:
tensor_one_d= tf.constant([1.0,2,3], dtype=tf.float32)
casted_tensor = tf.cast(tensor_one_d, dtype=tf.int16)
print(casted_tensor)
print(tensor_one_d)

tf.Tensor([1 2 3], shape=(3,), dtype=int16)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [9]:
tensor_bool = tf.constant([True, False, True])
tensor_string= tf.constant(["Hi","Hello"])
print(tensor_bool)
print(tensor_string)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)
tf.Tensor([b'Hi' b'Hello'], shape=(2,), dtype=string)


In [10]:
import numpy as np

In [11]:
np_array= np.array([1,2,3])
print(np_array)
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

[1 2 3]
tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [29]:
eye_tensor= tf.eye(
    num_rows=3,
    num_columns=3,
    batch_shape=[2,3],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)


tf.Tensor(
[[[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]


 [[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]], shape=(2, 3, 3, 3), dtype=float32)


In [34]:
fill_tensor= tf.fill(
    [2,3,4], 5, name=None, layout=None
)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(2, 3, 4), dtype=int32)


In [35]:
ones_tensor=tf.ones(
    [2,3,3],
    dtype=tf.dtypes.float32,
    name=None,
    layout=None
)
print(ones_tensor)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 3, 3), dtype=float32)


In [36]:
ones_like_tensor=tf.ones_like(
    ones_tensor
)
print(ones_like_tensor)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 3, 3), dtype=float32)


In [40]:
t = tf.constant([1,2,3])
tf.size(t, out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [42]:
random_tensor = tf.random.normal(
    [3,3],
    mean=0 .0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[-0.15765539  1.3139538  -0.9873057 ]
 [-1.1033739   0.07431085 -1.5090333 ]
 [-1.0620273   0.6440515   0.37542048]], shape=(3, 3), dtype=float32)


In [44]:
random_uniform =tf.random.uniform(
    [2,3],
    minval=0,
    maxval=8,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_uniform)

tf.Tensor(
[[1.5372877 2.6820745 3.5806885]
 [1.139184  2.0385933 6.3247805]], shape=(2, 3), dtype=float32)


In [45]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)


In [48]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)


In [64]:
tensor_indexed = tf.constant([1,4,5,6,2,4,100,99,34])
print(tensor_indexed)
print(tensor_indexed[0:4])
print(tensor_indexed[:4])
print(tensor_indexed[1:5])
print(tensor_indexed[4:-2])
print(tensor_indexed[1:6:2])

tf.Tensor([  1   4   5   6   2   4 100  99  34], shape=(9,), dtype=int32)
tf.Tensor([1 4 5 6], shape=(4,), dtype=int32)
tf.Tensor([1 4 5 6], shape=(4,), dtype=int32)
tf.Tensor([4 5 6 2], shape=(4,), dtype=int32)
tf.Tensor([  2   4 100], shape=(3,), dtype=int32)
tf.Tensor([4 6 4], shape=(3,), dtype=int32)


In [70]:
tensor_indexed_twod = tf.constant([[2,3,4,5],[3,4,5,6],[2,5,6,7]])
print(tensor_indexed_twod[0:3, 0:2])
print(tensor_indexed_twod[2, :])
print(tensor_indexed_twod[2, 1:])
print(tensor_indexed_twod[:,0])

tf.Tensor(
[[2 3]
 [3 4]
 [2 5]], shape=(3, 2), dtype=int32)
tf.Tensor([2 5 6 7], shape=(4,), dtype=int32)
tf.Tensor([5 6 7], shape=(3,), dtype=int32)
tf.Tensor([2 3 2], shape=(3,), dtype=int32)


In [57]:
tf.range(1,6)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>