<a href="https://colab.research.google.com/github/narain-priyanka/vision_machine_learning/blob/master/TensorFlow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [4]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [6]:
tensor_one_d = tf.constant([2,0,3])
print(tensor_one_d)

tf.Tensor([2 3], shape=(2,), dtype=int32)


In [8]:
tensor_two_d = tf.constant([[2,0,3],[1,0,2],[-1,0,3.0]]
                           )
print(tensor_two_d)

tf.Tensor(
[[ 2.  0.  3.]
 [ 1.  0.  2.]
 [-1.  0.  3.]], shape=(3, 3), dtype=float32)


In [11]:
tensor_three_d = tf.constant([
  [[2,0,3],
   [1,0,2]],
  [[2,0,3],
   [1,0,2]],
  [[2,0,3],
   [1,0,2]],
  [[2,0,3],
   [1,0,2]]
  ])
print(tensor_three_d)

tf.Tensor(
[[[2 0 3]
  [1 0 2]]

 [[2 0 3]
  [1 0 2]]

 [[2 0 3]
  [1 0 2]]

 [[2 0 3]
  [1 0 2]]], shape=(4, 2, 3), dtype=int32)


In [12]:
print(tensor_three_d.shape)

(4, 2, 3)


In [15]:
print(tensor_three_d.ndim)

3
