<a href="https://colab.research.google.com/github/narain-priyanka/vision_machine_learning/blob/master/Tesnor%26Variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import tensorflow as tf
import numpy as np

In [2]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
tensor_2d = tf.constant([
      [2,-3,1],
      [2,-3,1]
])
print(tensor_2d)

tf.Tensor(
[[ 2 -3  1]
 [ 2 -3  1]], shape=(2, 3), dtype=int32)


In [4]:
tensor_one_d= tf.constant([1.0,2,3], dtype=tf.float32)
casted_tensor = tf.cast(tensor_one_d, dtype=tf.int16)
print(casted_tensor)
print(tensor_one_d)

tf.Tensor([1 2 3], shape=(3,), dtype=int16)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [5]:
tensor_bool = tf.constant([True, False, True])
tensor_string= tf.constant(["Hi","Hello"])
print(tensor_bool)
print(tensor_string)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)
tf.Tensor([b'Hi' b'Hello'], shape=(2,), dtype=string)


In [6]:
import numpy as np

In [7]:
np_array= np.array([1,2,3])
print(np_array)
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

[1 2 3]
tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [8]:
eye_tensor= tf.eye(
    num_rows=3,
    num_columns=3,
    batch_shape=[2,3],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)


tf.Tensor(
[[[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]


 [[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]], shape=(2, 3, 3, 3), dtype=float32)


In [9]:
fill_tensor= tf.fill(
    [2,3,4], 5, name=None, layout=None
)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(2, 3, 4), dtype=int32)


In [10]:
ones_tensor=tf.ones(
    [2,3,3],
    dtype=tf.dtypes.float32,
    name=None,
    layout=None
)
print(ones_tensor)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 3, 3), dtype=float32)


In [11]:
ones_like_tensor=tf.ones_like(
    ones_tensor
)
print(ones_like_tensor)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 3, 3), dtype=float32)


In [12]:
t = tf.constant([1,2,3])
tf.size(t, out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [13]:
random_tensor = tf.random.normal(
    [3,3],
    mean=0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[-0.02774657  1.2975107   0.49835905]
 [-1.4062138  -2.0458696  -0.1148613 ]
 [ 0.28334266  1.9082602   1.3942025 ]], shape=(3, 3), dtype=float32)


In [14]:
random_uniform =tf.random.uniform(
    [2,3],
    minval=0,
    maxval=8,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_uniform)

tf.Tensor(
[[1.7420044  6.352516   6.323971  ]
 [1.7201462  5.2708883  0.29879856]], shape=(2, 3), dtype=float32)


In [15]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)


In [16]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)


In [17]:
tensor_indexed = tf.constant([1,4,5,6,2,4,100,99,34])
print(tensor_indexed)
print(tensor_indexed[0:4])
print(tensor_indexed[:4])
print(tensor_indexed[1:5])
print(tensor_indexed[4:-2])
print(tensor_indexed[1:6:2])

tf.Tensor([  1   4   5   6   2   4 100  99  34], shape=(9,), dtype=int32)
tf.Tensor([1 4 5 6], shape=(4,), dtype=int32)
tf.Tensor([1 4 5 6], shape=(4,), dtype=int32)
tf.Tensor([4 5 6 2], shape=(4,), dtype=int32)
tf.Tensor([  2   4 100], shape=(3,), dtype=int32)
tf.Tensor([4 6 4], shape=(3,), dtype=int32)


In [18]:
tensor_indexed_twod = tf.constant([[2,3,4,5],[3,4,5,6],[2,5,6,7]])
print(tensor_indexed_twod[0:3, 0:2])
print(tensor_indexed_twod[2, :])
print(tensor_indexed_twod[2, 1:])
print(tensor_indexed_twod[:,0])
print(tensor_indexed_twod[...,0])

tf.Tensor(
[[2 3]
 [3 4]
 [2 5]], shape=(3, 2), dtype=int32)
tf.Tensor([2 5 6 7], shape=(4,), dtype=int32)
tf.Tensor([5 6 7], shape=(3,), dtype=int32)
tf.Tensor([2 3 2], shape=(3,), dtype=int32)
tf.Tensor([2 3 2], shape=(3,), dtype=int32)


In [19]:
tf.range(1,6)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [20]:
tensor_indexed_3D = tf.constant([
  [[2,3,4,5],[3,4,5,6]],
  [[2,3,4,5],[3,4,5,6]]])
print(tensor_indexed_3D)
print(tensor_indexed_3D[0,:,:])
print(tensor_indexed_3D[...,:,3])

tf.Tensor(
[[[2 3 4 5]
  [3 4 5 6]]

 [[2 3 4 5]
  [3 4 5 6]]], shape=(2, 2, 4), dtype=int32)
tf.Tensor(
[[2 3 4 5]
 [3 4 5 6]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[5 6]
 [5 6]], shape=(2, 2), dtype=int32)


In [21]:
# if 'input' is [[ 0,  1,  2, 3]
#                [-1,  0,  1, 2]
#                [-2, -1,  0, 1]
#                [-3, -2, -1, 0]],
# you can read all these in linalg section

tensor_2d = tf.constant([ [ 0,  1,  2, 3],
                          [-1,  1,  5, 2],
                          [-2, -3,  2, 1],
                          [-3, -2, -1, 0]])

tensor_outd = tf.constant([ [ 0,  1,  2, 3],
                          [-1,  0,  5, 2],
                          [-2, -1,  0, 1],
                          [-3, -2, -1, 0]])
tf.linalg.band_part(tensor_2d, -1, 3)



<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [-1,  1,  5,  2],
       [-2, -3,  2,  1],
       [-3, -2, -1,  0]], dtype=int32)>

In [22]:
tensor_2d = tf.constant([ [ 0,  1,  2, 3],
                          [-1,  1,  5, 2],
                          [-2, -3,  2, 1],
                          [-3, -2, -1, 0]], dtype=tf.float32)
tensor_inv=tf.linalg.inv(tensor_2d)
print(tensor_inv)
print(tensor_inv@tensor_2d)  # this gives the identity matrix where diagonals are all 1 and rest around 0)

tf.Tensor(
[[ 5.5555534e-02 -2.0000002e-01  2.3333335e-01 -4.2222226e-01]
 [ 3.5762785e-08  2.0000003e-01 -4.0000004e-01  2.0000002e-01]
 [-1.6666667e-01  1.9999999e-01  1.0000001e-01 -1.3333334e-01]
 [ 4.4444445e-01 -2.0000000e-01  6.6666655e-02  2.2222228e-02]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[ 1.0000001e+00 -5.9604645e-08 -1.1920929e-07 -8.9406967e-08]
 [ 0.0000000e+00  1.0000001e+00  5.9604645e-08  1.4901161e-07]
 [ 1.4901161e-08 -2.9802322e-08  1.0000000e+00  0.0000000e+00]
 [ 1.4901161e-08  2.9802322e-08 -1.1920929e-07  1.0000000e+00]], shape=(4, 4), dtype=float32)


In [32]:
# enisum operators @2:55
A = np.array([ [ 0,  1,  2, 3],
               [-1,  3,  5, 2],
               [-2, -3,  4, 1],
               [-3, -2, -1, 0]])

B = np.array([ [ 0,  1,  2, 3],
               [-1,  0,  5, 2],
               [-2, -1,  0, 1],
               [-3, -2, -1, 0]])
print(np.matmul(A,B)) #for the matrix multiplication necessary codition is ij,jk
print(np.einsum("ij,jk->ik", A,B))

#lement wise multiplication ncessary condition is matrix has same shape ij,ij
# which is called Hardamond multiplication
print(A*B)
#how to write it in einsum
print(np.einsum("ij,ij->ij", A,B))

[[-14  -8   2   4]
 [-19 -10  11   8]
 [ -8  -8 -20  -8]
 [  4  -2 -16 -14]]
[[-14  -8   2   4]
 [-19 -10  11   8]
 [ -8  -8 -20  -8]
 [  4  -2 -16 -14]]
[[ 0  1  4  9]
 [ 1  0 25  4]
 [ 4  3  0  1]
 [ 9  4  1  0]]
[[ 0  1  4  9]
 [ 1  0 25  4]
 [ 4  3  0  1]
 [ 9  4  1  0]]


In [34]:
  # write matrix transpose using einsum operator
  # transpose is where a matrix with m*n dimension is truned into n*m dimension
  A = np.array([ [ 0,  1,  2, 3],
               [-1,  3,  5, 2],
               [-2, -3,  4, 1],
               [-3, -2, -1, 0]])
  print(A.T, "\n") # normal way of doing it via T function
  print(np.einsum("ij->ji",A))

[[ 0 -1 -2 -3]
 [ 1  3 -3 -2]
 [ 2  5  4 -1]
 [ 3  2  1  0]] 

[[ 0 -1 -2 -3]
 [ 1  3 -3 -2]
 [ 2  5  4 -1]
 [ 3  2  1  0]]


In [40]:
#common tensorflow functions
# add one more axis
tensor_oned = tf.constant([2,3,4])
print(tensor_oned.shape)
print(tf.expand_dims(tensor_oned,axis=0))

tf.squeeze() # does opposite of expand

(3,)
tf.Tensor([[2 3 4]], shape=(1, 3), dtype=int32)


In [44]:
#ragged tensor
#sparse tensor
#string
#variables
x = tf.constant([1,2]) #constants are tensors whose values cannot be changed during execution.

In [49]:
#variables Variables are tensors whose values can be modified during execution.
x_var = tf.Variable(x, name='var1')
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>


In [51]:
x_var.assign_add([1,3])
x_var.assign_add([3,4])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 6, 12], dtype=int32)>

In [58]:
with tf.device('CPU:0'):
  x_var = tf.Variable(0.2)

with tf.device('GPU:0'):
  x_tensor = tf.Variable(0.2)

print(x_var.device)
print(x_tensor.device)

/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:CPU:0


In [62]:
with tf.device('CPU:0'):
  x_1 = tf.constant([2,3,4]) # This creates a 1-dimensional tensor (vector) with a shape of (3,), indicating that it has a length of 3 along that axis.
  x_2 = tf.constant([2]) # valid as broadcasting will happen in this case when length is 1

with tf.device('GPU:0'):
  x_3 = x_1 + x_2

print(x_1, x_1.device)
print(x_2, x_2.device)
print(x_3, x_3.device)

tf.Tensor([2 3 4], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([2], shape=(1,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([4 5 6], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
